---
name: Backup Supabase Database to Google Drive

on:
  schedule:
    - cron: 0 9 */3 * *  # Runs at 9:00 AM UTC every 3 days
  workflow_dispatch:  # Manual trigger from the GitHub UI

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump database
        id: dump
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          filename=$(date +'%Y-%m-%d_%H-%M-%S').dump
          pg_dump "$DATABASE_URL" \
            --format=custom \
            --file="$filename"
          echo "filename=$filename" >> "$GITHUB_OUTPUT"

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Upload backup to Supabase Storage
        env:
          SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |-
          supabase login --token $SUPABASE_TOKEN

          supabase link --project-ref ${SUPABASE_PROJECT_ID} --password ${DATABASE_PASSWORD}

          supabase storage cp ${{ steps.dump.outputs.filename }} ss:///$SUPABASE_BUCKET/${{ steps.dump.outputs.filename }} --experimental
